3a edit

diff --git a/.github/workflows/demo3.yml b/.github/workflows/demo3.yml
--- a/.github/workflows/demo3.yml
+++ b/.github/workflows/demo3.yml
@@ -40,8 +40,8 @@ jobs:
          echo "Listing files in the repository(${{ github.workspace }}).."
          ls ${{ github.workspace }}
      - run: echo "Job's status is ${{ job.status }}"
-     - name: Faking an error
-       run: |
-          echo "Before Faking an error"
-          exit 1
-          echo "After faking an error"
+    # - name: Faking an error
+    #    run: |
+    #       echo "Before Faking an error"
+    #       exit 1
+    #       echo "After faking an error" 
